server:
  port: 12000
spring:
  application:
    name: config-server-bus
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jk349262999/SpringCloud-Finchley # 配置git仓库的地址
          search-paths: config-repo
    bus:
      enabled: true
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh