spring:
  application:
    name: gateway-zuul
server:
  port: 14000
zuul:
  routes:
    # 转发服务id
    api-example-serviceid:
      path: /eureka-consumer/**
      service-id: eureka-consumer
    # 转发网址
    api-example-website:
      path: /baidu/**
      service-id: https://www.baidu.com/
    # 默认自动配置的转发规则：地址转换为服务id，类似api-example-serviceid
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/