spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ # 指定 Eureka 注册中心的地址
#    register-with-eureka: false #自身是消费者，不注册为服务提供者
server:
  port: 9000 # 分别为 9000、9001、9002